### ISSUE TITLE
Fenix 8 support

### ISSUE THREAD

**Issue by nehasvit** [buessow/garmin#1]
Hello,
I would like to ask if it would be possible to add support for fenix 8. Specifically the solar 47 version.
Thank you

**Comment by buessow** [comment]
I've added watch face support for fenix 8* and venu 3. The data field and
glance will follow. Please let me know if it works.

Cheers
Robert

Robert Buessow . Mobile: +41 78 899 8296

**Comment by nehasvit** [comment]
Yes, the watchface works.
Thank you for the quick update.

**Comment by buessow** [comment]
The datafield is now also supported. Sorry, that it took so long. Please
let me know if it works.

Thanks
Robert

Robert Buessow . Mobile: +41 78 899 8296
